import { useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useBeerData } from "../hooks/useBeerData";

const inter = Inter({ subsets: ["latin"] });

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function Home() {
  const [currentPage, setCurrentPage] = useState(1);
  const { data, isLoading, isError } = useBeerData(currentPage);

  const handleNextPage = () => setCurrentPage((prev) => prev + 1);
  const handlePrevPage = () => setCurrentPage((prev) => Math.max(prev - 1, 1));

  if (isLoading) return <p>Loading...</p>;
  if (isError) return <p>Error loading data</p>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <h1>Beer List</h1>
        <ul className={styles.beerList}>
          {data.map((beer) => (
            <li key={beer.id} className={styles.beerItem}>
              <h2>{beer.name}</h2>
              <p>{beer.tagline}</p>
            </li>
          ))}
        </ul>
        <div className={styles.pagination}>
          <button
            className={styles.button}
            onClick={handlePrevPage}
            disabled={currentPage === 1}
          >
            Previous Page
          </button>
          <span>Page {currentPage}</span>
          <button className={styles.button} onClick={handleNextPage}>
            Next Page
          </button>
        </div>
      </main>
    </>
  );
}
